---
# tasks file for ansible-mdadm
#
#- include_tasks: el.yml
#  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_distribution == "Ubuntu"  

- include_tasks: wipe_disks.yml
  when: >
        mdadm_force_wipe is defined and
        mdadm_force_wipe
        
- include_tasks: arrays.yml
  when: ansible_distribution == "Ubuntu"

# - include_tasks: deploy.ubuntu.yml
#   when: ansible_distribution == "Ubuntu"
      