- name: Install xrdp prerequisites (deb)
  apt:
    name: "{{ xrdp_packages }}"
    state: present
  vars:
    xrdp_packages:
      - xrdp
      - xfce4
      - xfce4-terminal
      - gnome-icon-theme
      - tango-icon-theme
  when: ansible_os_family == "Debian"
  become: true

- name: Set .xsession file for XRDP
  copy:
    src: xsession-xrdp
    dest: "/home/{{ mcdonalds_primary_user }}/.xsession"
  become: true
  become_user: "{{ mcdonalds_primary_user }}"

- name: Set startwm.sh file for XRDP
  copy:
    src: xrdp-startwm.sh
    dest: /etc/xrdp/startwm.sh
    mode: 0755
  become: true

- name: Restart xrdp service
  service:
    name: xrdp
    state: restarted
  become: true
