- name: Disable apport
  lineinfile:
    path: /etc/default/apport
    regexp: '^enabled='
    line: 'enabled=0'
  become: true

- name: Stop apport service
  service:
    name: apport
    state: stopped
  become: true
  tags: debug
