- name: Copy login branding images
  copy:
    src: "{{ item }}"
    dest: "/usr/share/pixmaps/{{ item }}"
  loop:
    - poweredby_ipconfigure.png
    - poweredby_ipconfigure.svg
    - orchid_background.jpg
    - orchid_background_blank.png
  become: true

- name: Install python-lxml (deb)
  apt:
    name: python-lxml
    state: latest
  become: true
  when: ansible_os_family == "Debian"

- name: Install python-lxml (rpm)
  yum:
    name: python-lxml
    state: latest
  become: true
  when: ansible_os_family == "RedHat"

- name: Brand lightdm
  include_tasks: lightdm-branding.yml
  when: ansible_facts.packages.lightdm is defined

- name: Brand gdm
  include_tasks: gdm-branding.yml
  when: ansible_facts.packages.gdm is defined or ansible_facts.packages.gdm3 is defined
