- name: Set lightdm Unity greeter background
  xml:
    path: /usr/share/glib-2.0/schemas/com.canonical.unity-greeter.gschema.xml
    xpath: '/schemalist[@gettext-domain="unity-greeter"]/schema[@id="com.canonical.unity-greeter"]/key[@name="background"]/default'
    value: "'/usr/share/pixmaps/orchid_background_blank.png'"
  become: true

- name: Set lightdm Unity greeter logo
  xml:
    path: /usr/share/glib-2.0/schemas/com.canonical.unity-greeter.gschema.xml
    xpath: '/schemalist[@gettext-domain="unity-greeter"]/schema[@id="com.canonical.unity-greeter"]/key[@name="logo"]/default'
    value: "'/usr/share/pixmaps/poweredby_ipconfigure.png'"
  become: true

- name: Set lightdm Unity greeter to not draw grid
  xml:
    path: /usr/share/glib-2.0/schemas/com.canonical.unity-greeter.gschema.xml
    xpath: '/schemalist[@gettext-domain="unity-greeter"]/schema[@id="com.canonical.unity-greeter"]/key[@name="draw-grid"]/default'
    value: 'false'
  become: true

- name: Set lightdm Unity greeter to not draw user-defined backgrounds
  xml:
    path: /usr/share/glib-2.0/schemas/com.canonical.unity-greeter.gschema.xml
    xpath: '/schemalist[@gettext-domain="unity-greeter"]/schema[@id="com.canonical.unity-greeter"]/key[@name="draw-user-backgrounds"]/default'
    value: 'false'
  become: true

- name: Set lightdm Unity greeter to never blank the screen
  xml:
    path: /usr/share/glib-2.0/schemas/com.canonical.unity-greeter.gschema.xml
    xpath: '/schemalist[@gettext-domain="unity-greeter"]/schema[@id="com.canonical.unity-greeter"]/key[@name="idle-timeout"]/default'
    value: '0'
  become: true

- name: Rebuild XML schema for lightdm Unity greeter
  command: /usr/bin/glib-compile-schemas --strict /usr/share/glib-2.0/schemas/
  register: schema_compile_status
  failed_when: schema_compile_status.rc != 0
  become: true

- name: Restart lightdm service
  service:
    name: lightdm
    state: restarted
  become: true
