---
# tasks file for server-access
- name: "Look for user"
  raw: |
        if getent passwd "{{ lookup('env','USER') }}" > /dev/null 2>&1; then
          echo "YES, {{ lookup('env','USER') }} exists"
        else
          echo "NO, {{ lookup('env','USER') }} does not exist in /etc/passwd. {{ inventory_hostname }} connected to Active Directory."
        fi
  no_log: true
  register: lookforuser

- debug:
    msg: "{{ inventory_hostname }}  {{ lookforuser.stdout_lines }}"
