- name: Install dash-to-dock GNOME extension (RedHat)
  yum:
    name: gnome-shell-extension-dash-to-dock
    state: latest
  become: true

- name: Remove window-list GNOME extension (RedHat)
  yum:
    name: gnome-shell-extension-window-list
    state: absent
  become: true

- name: Configure dash-to-dock GNOME extension (RedHat)
  shell: |
    dbus-launch gsettings set org.gnome.shell enabled-extensions "['dash-to-dock@micxgx.gmail.com']"
    dbus-launch gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'previews'
    dbus-launch gsettings set org.gnome.shell.extensions.dash-to-dock icon-fixed-size true
    dbus-launch gsettings set org.gnome.shell.extensions.dash-to-dock intellihide-mode 'ALL_WINDOWS'
    dbus-launch gsettings set org.gnome.shell.extensions.dash-to-dock extend-height true
    dbus-launch gsettings set org.gnome.shell.extensions.dash-to-dock transparency-mode 'ADAPTIVE'
    dbus-launch gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed true
  become: true
  become_user: "{{ steelfin_user_account }}"
