- block:
    - name: Copy Chrome 34 installer (deb)
      copy:
        src: "{{ item }}"
        dest: "/tmp/{{ item }}"
      loop:
        - "{{ chrome_deb }}"
        - "{{ libnss3_deb }}"
        - "{{ libnss3_tools_deb }}"
        - "{{ libnss3_nssdb_deb }}"

    - name: Install Chrome 34 (deb)
      apt:
        deb: "/tmp/{{ chrome_deb }}"
        state: present
      become: true

    - name: Remove Chrome 34 repo (deb)
      file:
        path: "/etc/apt/sources.list.d/google-chrome.list"
        state: absent
      become: true

    - name: Get installed package facts
      package_facts:

    # Do the following ONLY if libnss3 and friends aren't installed and the right version.
    - block: 
        - name: Install libnss3 latest (deb)
          apt:
            name: "{{ packages }}"
            state: latest
            force: yes
          vars:
            packages:
              - libnss3-nssdb
              - libnss3
              - libnss3-tools
          become: true
    
        - name: Install libnss3 downgraded (deb)
          apt: 
            deb: "/tmp/{{ item }}"
            state: present
            dpkg_options: force-downgrade
            force: yes
          loop:
            - "{{ libnss3_nssdb_deb }}"
            - "{{ libnss3_deb }}"
            - "{{ libnss3_tools_deb }}"
          become: true
      when: not ( ansible_facts.packages.libnss3.version is defined 
            and ansible_facts.packages.libnss3.version == "2:3.15.4-1ubuntu7" )
            
    - name: Lock Chrome34 and libnss versions (deb)
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - google-chrome-stable
        - libnss3-nssdb
        - libnss3
        - libnss3-tools
      become: true
    
  vars:
    chrome_deb: "google-chrome-stable_34.0.1847.137-1_amd64.deb"
    libnss3_deb: "libnss3_3.15.4-1ubuntu7_amd64.deb"
    libnss3_tools_deb: "libnss3-tools_3.15.4-1ubuntu7_amd64.deb"
    libnss3_nssdb_deb: "libnss3-nssdb_3.15.4-1ubuntu7_all.deb"
