###########################
# RPM VERSION
###########################
- block:
    - name: Find FBGST installer (rpm)
      find:
        paths: /opt/orchid/share/orchid-html/software
        patterns: "FBGST*.rpm"
      register: fbgst_installer
      failed_when: fbgst_installer.files[0].path is not defined

    - name: Configure SELinux to allow FBGST (rpm)
      seboolean:
        name: unconfined_mozilla_plugin_transition
        state: false
        persistent: yes
      become: true

    - name: Install FBGST (rpm)
      yum:
        name: "{{ fbgst_installer.files[0].path }}"
        state: present 
      become: true
  when: ansible_os_family == "RedHat"

###########################
# DEBIAN VERSION
###########################
- block: 
    - name: Find FBGST installer (deb)
      find:
        paths: /opt/orchid/share/orchid-html/software
        patterns: "FBGST*.deb"
      register: fbgst_installer
      failed_when: fbgst_installer.files[0].path is not defined

    - name: Install FBGST (deb)
      apt:
        deb: "{{ fbgst_installer.files[0].path }}"
        state: present 
      become: true

    # FBGST's bundled libraries conflict with Ubuntu 18.04, so we need to remove
    # them from ld.so.conf.d, and make it so they're only loaded via LD_LIBRARY_PATH
    # and only with firefox-esr.
    - block:
        - name: Remove FBGST ld.so.conf.d entry (Ubuntu 18.04)
          file:
            path: /etc/ld.so.conf.d/fbgst.conf
            state: absent

        - name: Update dynamic linker (Ubuntu 18.04)
          command: ldconfig
          become: true
 
        - name: Update Firefox ESR desktop file (Ubuntu 18.04)
          lineinfile:
            path: /usr/share/applications/firefox-esr.desktop
            regexp: '^Exec='
            line: 'Exec=env LD_LIBRARY_PATH=/opt/fbgst/lib /usr/lib/firefox-esr/firefox-esr %u'

      when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"
      become: true

  when: ansible_os_family == "Debian"
