##################################3
# INSTALL WEB BROWSERS
##################################3
- name: Install Chrome latest
  include_tasks: browser-chrome-latest.yml
  when: not (ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04")

- name: Install Firefox 52 ESR
  include_tasks: browser-firefox-esr.yml

- name: Install Chrome 34
  include_tasks: browser-chrome34.yml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

- name: Install FBGST
  include_tasks: fbgst.yml
