#cat > ${WORKSPACE}/ansible_license_uri.yaml <<EOF
---
- hosts: "localhost"
  connection: local
  gather_facts: true
  vars:
    myurl: http://{{ ansible_host }}/service/discoverable/orchids
    activation_url: https://www.orchidsecurity.com/activation/
    target_connection: http://{{ ansible_host }}/service/license-session
    activation_code: "{{ inventory_hostname }}"
    location_description: "{{ lookup('env','LOCATION_DESCRIPTION') }}"
    jenkins_workspace: "{{ lookup('env','WORKSPACE') }}"    
  vars_files:

  tasks:   

  - name: Retrieve Orchid MID
    uri:
      url: "{{ myurl }}"
      force_basic_auth: yes
      user: admin
      password: "0rc#1d"
      timeout: 20
    register: machineid
    
  - name: DEBUG Retrieve Orchid MID
    debug:
      msg: "{{ machineid.json.orchids[0].mid }}"

  - name: Post to retrieve Licence code  
    uri:
      url: "{{ activation_url }}"
      method: POST
      body: "activation_code={{ activation_code }}\
      &machine_id={{ machineid.json.orchids[0].mid }}\
      &location_description={{ location_description }}\
      &headless=1"
      return_content: yes
      status_code: 200
      headers:
        Content-Type: "application/x-www-form-urlencoded"
    register: lic_code  

  - name: DEBUG Post to retrieve Licence code
    debug:
      msg: "{{ lic_code.content }}" 

  - name: Activate Orchid license
    uri:
      url: "{{ target_connection }}"
      method: POST
      user: admin
      password: "0rc#1d"
      body: "{{ lic_code.content | regex_replace('^\"', '\"$') }}"
      force_basic_auth: yes
      status_code: 201
      body_format: json 
    register: act_orchid         

  - name: DEBUG Activate Orchid license
    debug:
      msg: "{{ act_orchid }}"


#EOF