- name: (Re-)populate service facts
  service_facts:

- name: "Set Orchid Core VMS service state (systemd) to {{ orchid_service_state }}"
  systemd:
    name: orchid
    state: "{{ orchid_service_state }}"
  when: "'orchid.service' in ansible_facts.services"
  become: true

- block:
    - name: "Set monit service state (sysvinit) to {{ orchid_service_state }}"
      service:
        name: monit
        state: "{{ orchid_service_state }}"

    - name: "Set Orchid Core VMS service state (sysvinit) to {{ orchid_service_state }}"
      service:
        name: orchid
        state: "{{ orchid_service_state }}"

  become: true
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04" and ansible_facts.services["orchid"] is defined
