pipeline {
    agent any

    stages {
        stage('Run Ansible Access operation'){
        
            steps {

            wrap([$class: 'AnsiColorBuildWrapper', colorMapName: "xterm"]) {
                    echo 'Validate Access'
                    //sh 'ansible-playbook -i dev-servers site.yml'
                    ansiblePlaybook credentialsId: '62c93b86-c4ba-483c-a696-8180694ce559',
                    installation: 'ansible', 
                        inventory: "~/inventory",
                    limit: 'all',
                    playbook: 'roletest/server_access_status.yml',
                    colorized: true
                }
            }
        }
        stage('API tests'){
            steps {
                echo 'Executing API tests... ya right!!!'
            }
        }

        stage('Performance tests'){
            steps {
                sh '''#!/bin/bash -l
                      echo $0
                      # more stuff I needed to do,
                      newman run ~/Downloads/response.json
                '''
            }
        }

        stage('Demo Performance'){
            steps {
                echo 'Clap if you liked the demo!'
            }
        }

    }
}

